# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hownHTn5ovQquAcXvrSsFP6LDjZ51b8h
"""

import os
from getpass import getpass

from langchain_google_genai import ChatGoogleGenerativeAI
from langgraph.graph import StateGraph, START, END
from typing import TypedDict

!pip install -q -U langchain langchain-google-genai langgraph

import os
from getpass import getpass

api_key = getpass("Enter your Gemini API Key: ")

os.environ["GOOGLE_API_KEY"] = api_key

print("API key loaded:", bool(os.environ.get("GOOGLE_API_KEY")))

llm = ChatGoogleGenerativeAI(
    model="gemini-3.5-flash",
    api_key=api_key,
    temperature=0.3
)

response = llm.invoke("Hello Gemini")

print(response.content)

from typing import TypedDict
from langgraph.graph import StateGraph, START, END

class BudgetState(TypedDict):
    financial_data: str
    expense_analysis: str
    budget_plan: str
    savings_plan: str
    final_report: str

def expense_agent(state: BudgetState):

    print("\n" + "="*50)
    print("🔍 EXPENSE ANALYSIS AGENT")
    print("="*50)

    prompt = f"""
You are an Expense Analysis AI Agent.

Analyze the following personal financial information:

{state['financial_data']}

Perform the following tasks:

1. Calculate total monthly expenses.
2. Calculate remaining income.
3. Calculate the percentage of income spent.
4. Identify the three largest expenses.
5. Identify expenses that could potentially be reduced.
6. Provide clear financial observations.

Your output will be passed to another AI agent called
the Budget Agent. Therefore, provide structured and
accurate information.

Do not invent financial data.
"""

    response = llm.invoke(prompt)

    print(response.content)

    return {
        "expense_analysis": response.content
    }

def expense_agent(state: BudgetState):

    print("\n" + "="*50)
    print("🔍 EXPENSE ANALYSIS AGENT")
    print("="*50)

    prompt = f"""
You are an Expense Analysis AI Agent.

Analyze the following personal financial information:

{state['financial_data']}

Perform the following tasks:

1. Calculate total monthly expenses.
2. Calculate remaining income.
3. Calculate the percentage of income spent.
4. Identify the three largest expenses.
5. Identify expenses that could potentially be reduced.
6. Provide clear financial observations.

Your output will be passed to another AI agent called
the Budget Agent. Therefore, provide structured and
accurate information.

Do not invent financial data.
"""

    response = llm.invoke(prompt)

    print(response.content)

    return {
        "expense_analysis": response.content
    }

def budget_agent(state: BudgetState):

    print("\n" + "="*50)
    print("💰 BUDGET MANAGEMENT AGENT")
    print("="*50)

    prompt = f"""
You are a Personal Budget Management AI Agent.

The user provided the following financial information:

{state['financial_data']}

The Expense Analysis Agent analyzed the data and provided:

{state['expense_analysis']}

Now create a practical monthly budget.

The user's goal is to save at least ₹8,000 per month.

Your task:

1. Analyze the Expense Agent's findings.
2. Identify essential and non-essential expenses.
3. Recommend spending limits.
4. Suggest where expenses should be reduced.
5. Create a monthly budget.
6. Ensure the user can save at least ₹8,000 if financially possible.

Explain your reasoning clearly.

Your output will be passed to the Savings Agent.
"""

    response = llm.invoke(prompt)

    print(response.content)

    return {
        "budget_plan": response.content
    }

def savings_agent(state: BudgetState):

    print("\n" + "="*50)
    print("💵 SAVINGS ADVISOR AGENT")
    print("="*50)

    prompt = f"""
You are a Savings Advisor AI Agent.

Here is the user's financial information:

{state['financial_data']}

Here is the Expense Agent's analysis:

{state['expense_analysis']}

Here is the Budget Agent's proposed budget:

{state['budget_plan']}

Now analyze the proposed budget.

Determine:

1. Is saving ₹8,000 per month realistic?
2. Which expenses should be reduced?
3. How much can realistically be saved?
4. What practical strategies can increase savings?
5. Provide 5 actionable savings recommendations.

Your output will be passed to the Report Agent.
"""

    response = llm.invoke(prompt)

    print(response.content)

    return {
        "savings_plan": response.content
    }

def report_agent(state: BudgetState):

    print("\n" + "="*50)
    print("📊 FINANCIAL REPORT AGENT")
    print("="*50)

    prompt = f"""
You are a Financial Report AI Agent.

Create a final personal financial report.

USER FINANCIAL DATA:
{state['financial_data']}

EXPENSE ANALYSIS:
{state['expense_analysis']}

BUDGET PLAN:
{state['budget_plan']}

SAVINGS PLAN:
{state['savings_plan']}

Create a professional final report with these sections:

1. Financial Overview
2. Income Summary
3. Expense Analysis
4. Current Financial Position
5. Recommended Monthly Budget
6. Savings Recommendations
7. Final Conclusion

The report should be clear, concise, and easy for
a normal user to understand.

Do not invent any information that is not present
in the provided data.
"""

    response = llm.invoke(prompt)

    print(response.content)

    return {
        "final_report": response.content
    }

financial_data = """
Monthly Income: ₹50,000

Monthly Expenses:

Rent: ₹20,000
Food: ₹10,000
Transportation: ₹5,000
Shopping: ₹8,000
Entertainment: ₹3,000
Utilities: ₹2,000

Financial Goal:
The user wants to save at least ₹8,000 per month.
"""

workflow = StateGraph(BudgetState)

workflow.add_node("expense_agent", expense_agent)

workflow.add_node("budget_agent", budget_agent)

workflow.add_node("savings_agent", savings_agent)

workflow.add_node("report_agent", report_agent)

workflow.add_edge(
    START,
    "expense_agent"
)

workflow.add_edge(
    "expense_agent",
    "budget_agent"
)

workflow.add_edge(
    "budget_agent",
    "savings_agent"
)

workflow.add_edge(
    "savings_agent",
    "report_agent"
)

workflow.add_edge(
    "report_agent",
    END
)

app = workflow.compile()

initial_state = {
    "financial_data": financial_data,
    "expense_analysis": "",
    "budget_plan": "",
    "savings_plan": "",
    "final_report": ""
}

result = app.invoke(initial_state)

print("\n")
print("="*60)
print("           FINAL PERSONAL FINANCIAL REPORT")
print("="*60)

print(result["final_report"])